spring:
  application:
    name: bala-baqsham-lending
  mail:
    host: mail.balabaqsham.kz
    username: no-reply@balabaqsham.kz
    password: Viwdyq-mexpew-cirsa9
    port: 587
    protocol: smtp
    to: balabaqsha1@gmail.com
    properties:
      mail:
        smtp:
          ssl:
            trust: mail.balabaqsham.kz
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /lending
  forward-headers-strategy: native
  port: 9090


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  health:
    enabled: true

logging:
  level:
    ROOT: INFO
    kz.bala.baqsham.balabaqshamlending: INFO
logging.level.org.springframework.web: debug
