spring:
  application:
    name: unirate-platform-university
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5433/unirate_platform}
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver

server:
  port: 8082

logging:
  level:
    ROOT: INFO
    kz.mms.website_app: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true