spring:
  application:
    name: unirate-platform-registry
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5435/unirate_platform}
    username: postgres
    password: Tyxwy4-huhvuw-pamwyb
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    username: askar.abylkhaiyrov.00@gmail.com
    password: dssg nfoy sias moik
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jwt:
    secret: 8ac9dde390d3f6d48dba56ba14c37c26fd86af433abc08d174e35b951a713990
server:
  servlet:
    context-path: /registry
  port: 8087

springdoc:
  openapi:
    info:
      title: "Rest API for user-registry for UniRate Platform Registry"
      version: "1.0"
    servers:
      - url: "https://unirate.kz/registry"
        description: "Prod Server Running"
    components:
      securitySchemes:
        bearerAuth:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - bearerAuth: []

logging:
  level:
    ROOT: INFO
    kz.mms.website_app: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  health:
    enabled: true