spring:
  application:
    name: unirate-platform-api-gateway

server:
  port: 8081

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false