spring:
  application:
    name: unirate-platform-api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: unirate-platform-registry
          uri: lb://auth-service
          predicates:
            - Path=/auth-unirate-platform/**
          filters:
            - StripPrefix=1
        - id:  unirate-platform-university
          uri: lb://university-service
          predicates:
            - Path=/university-unirate-platform/**
          filters:
            - StripPrefix=1

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true