spring:
  application:
    name: unirate-platform-eureka-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

logging:
  level:
    ROOT: INFO
    kz.mms.website_app: INFO
