version: '3.8'
services:
  unirate-auth:
    build: .
    image: thqu1et/unirate-auth:latest
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/unirate-platform
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty
    depends_on:
      - db
  unirate-eureka-server:
    build: .
    image: thqu1et/unirate-eureka-server:latest
    ports:
      - "8761:8761"
  unirate-university:
    build: .
    image: thqu1et/unirate-university:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/unirate-platform
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: unirate-platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5435:5432"